In [1]:
import torch
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device

device(type='cuda', index=0)

In [ ]:
torch.cuda.is_available()

In [32]:
import torch.nn as nn

In [35]:
x = torch.rand(1,10)

In [36]:
x

tensor([[0.3472, 0.4268, 0.2569, 0.5298, 0.6082, 0.8769, 0.6337, 0.6792, 0.1333,
         0.0773]])

In [46]:
a = torch.floor(x).type(torch.bool)

In [66]:
c = torch.tensor([False, True, False])
b = x._indices()[:,c]

In [76]:
i = torch.LongTensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [77]:
torch.transpose(i, 0,1)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [39]:
import tensorflow as tf

In [87]:
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[3, 2])
b = tf.constant([7, 8, 9, 10, 11, 12], shape=[2, 3])
c = tf.matmul(a, b)

In [88]:
c

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [89]:
tf.reshape(c, [-1])

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 27,  30,  33,  61,  68,  75,  95, 106, 117], dtype=int32)>

In [40]:
num_nonzero_elems = 5
noise_shape = [num_nonzero_elems]

In [41]:
temp = tf.random.uniform(noise_shape)

In [43]:
tf.floor(temp)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>

In [ ]:
keep_prob = 0.7
random_tensor = keep_prob
temp = tf.random.uniform(noise_shape)
print(temp)
random_tensor += temp
print(random_tensor)

In [ ]:
random_tensor

In [28]:
import pandas as pd
import numpy as np

In [29]:
dataFile = pd.read_csv('../data/full_context_PeerRead.csv')

In [30]:
dataFile.head(100)


right_citated_text  \
0   andsyntactic parsing .Because RNNs make very f...   
1   .Because RNNs make very few domain-specific as...   
2   ; in a Pointer Network,the only way to generat...   
3   . Recently, nsur .  have shown superior perfor...   
4   model trained on the Google News dataset3.In a...   
..                                                ...   
95  to create a sentence embedding. Second, from e...   
96  for accelerating training. The network is opti...   
97  optimizer with learning rate of 0.001. We have...   
98  , and convolutional neural networks  have show...   
99  use concatenation and fully connected layers t...   

                                    left_citated_text  \
0   We conducted additional experiments on artific...   
1   We conducted additional experiments on artific...   
2   Reproducibility. All code, data, and experimen...   
3   st like CWS and POS tagging, automatic prosody...   
4   We begin by considering a document as the set ...   
..                                                ...   
95  For each word in the sentence we calculate var...   
96  For each Q-R pair we extract two sets of featu...   
97  For each Q-R pair we extract two sets of featu...   
98  Modeling textual or visual information with ve...   
99  In this paper, we propose to rely on ltimodal ...   

                                      source_abstract  \
0   Deep Neural Networks (DNNs) are powerful model...   
1   Syntactic parsing is a fundamental problem in ...   
2   We introduce a new neural architecture to lear...   
3   The recently introduced continuous Skip-gram m...   
4   The recently introduced continuous Skip-gram m...   
..                                                ...   
95  In this paper we compare different types of re...   
96  Training Deep Neural Networks is complicated b...   
97  We introduce Adam, an algorithm for first-orde...   
98  Deep Neural Networks (DNNs) are powerful model...   
99  We describe a very simple bag-of-words baselin...   

                                        source_author     source_id  \
0              ilya sutskever;oriol vinyals;quoc v le   1409.3215v1   
1   oriol vinyals;lukasz kaiser;terry koo;slav pet...   1412.7449v1   
2        oriol vinyals;meire fortunato;navdeep jaitly  1506.03134v1   
3   tomas mikolov;ilya sutskever;kai chen 0010;gre...   1310.4546v1   
4   tomas mikolov;ilya sutskever;kai chen 0010;gre...   1310.4546v1   
..                                                ...           ...   
95  junyoung chung;caglar gulcehre;kyunghyun cho;y...   1412.3555v1   
96                     sergey ioffe;christian szegedy  1502.03167v1   
97                         diederik p kingma;jimmy ba   1412.6980v1   
98             ilya sutskever;oriol vinyals;quoc v le   1409.3215v1   
99  bolei zhou;yuandong tian;sainbayar sukhbaatar;...  1512.02167v1   

                                         source_title source_venue  \
0   Sequence to Sequence Learning with Neural Netw...         NIPS   
1                       Grammar as a Foreign Language         NIPS   
2                                    Pointer Networks         NIPS   
3   Distributed Representations of Words and Phras...         NIPS   
4   Distributed Representations of Words and Phras...         NIPS   
..                                                ...          ...   
95  Empirical Evaluation of Gated Recurrent Neural...        arxiv   
96  Batch Normalization: Accelerating Deep Network...         ICML   
97         Adam: A Method for Stochastic Optimization         iclr   
98  Sequence to Sequence Learning with Neural Netw...         NIPS   
99      Simple Baseline for Visual Question Answering        arxiv   

    source_year     target_id  \
0        2014.0  1606.03622v1   
1        2014.0  1606.03622v1   
2        2015.0  1606.03622v1   
3        2013.0  1511.00360v1   
4        2013.0  1705.10900v1   
..          ...           ...   
95       2014.0  1708.05582v1   
96       2015.0  1708.

In [31]:
column = ['left_citated_text', 'right_citated_text', 'target_id', 'source_id', 'target_year','target_author', 'source_author']
frequency = 5

In [32]:
df = dataFile[column]
source_cut_data = df[['target_id', 'source_id']].drop_duplicates(subset=['target_id', 'source_id'])
source_cut = source_cut_data.source_id.value_counts()[(source_cut_data.source_id.value_counts() >= frequency)]

In [33]:
source_id = np.sort(source_cut.keys())
source_id
df = df.loc[df['source_id'].isin(source_id)]

In [103]:
source_id

array(['0705.4485v1', '0806.4686v1', '0812.4952v1', '0902.1284v1',
       '0902.2206v1', '0907.1815v1', '0911.5708v1', '0912.0071v1',
       '0912.3995v1', '1006.2588v1', '1010.3091v1', '1010.5511v1',
       '1103.0398v1', '1104.4803v1', '1105.1033v1', '1105.5379v1',
       '1106.2436v1', '1106.4574v1', '1107.4080v1', '1107.4557v1',
       '1109.3701v1', '1109.3843v1', '1109.5647v1', '1109.6841v1',
       '1112.6209v1', '1201.0292v1', '1201.0490v1', '1202.6258v1',
       '1204.0136v1', '1204.2742v1', '1204.3514v1', '1204.3968v1',
       '1204.6703v1', '1205.2661v1', '1206.1106v1', '1206.1270v1',
       '1206.2944v1', '1206.3255v1', '1206.4657v1', '1206.4683v1',
       '1206.6230v1', '1206.6380v1', '1206.6389v1', '1206.6392v1',
       '1206.6398v1', '1206.6400v1', '1206.6417v1', '1206.6418v1',
       '1206.6423v1', '1206.6426v1', '1206.6430v1', '1206.6448v1',
       '1206.6487v1', '1207.4404v1', '1207.4747v1', '1209.3352v1',
       '1210.5644v1', '1211.3966v1', '1211.5063v1', '1211.5590

In [101]:
df

left_citated_text  \
0      We conducted additional experiments on artific...   
1      We conducted additional experiments on artific...   
2      Reproducibility. All code, data, and experimen...   
3      st like CWS and POS tagging, automatic prosody...   
4      We begin by considering a document as the set ...   
...                                                  ...   
16664  The final  argument tells LLAMA whether low pe...   
16665  This approach works reasonably well, but does ...   
16666  In addition to the symmetry and replacement si...   
16667  Fig. 10 shows histograms of the execution time...   
16668  As we can see from Eq. , the target of the lea...   

                                      right_citated_text     target_id  \
0      andsyntactic parsing .Because RNNs make very f...  1606.03622v1   
1      .Because RNNs make very few domain-specific as...  1606.03622v1   
2      ; in a Pointer Network,the only way to generat...  1606.03622v1   
3      . Recently, nsur .  have shown superior perfor...  1511.00360v1   
4      model trained on the Google News dataset3.In a...  1705.10900v1   
...                                                  ...           ...   
16664  . For each instance, 36 features weremeasured....   1306.1031v1   
16665  on the POS sequences in PTB trainingset.The re...  1610.03946v1   
16666  and nia Treebank7.When evaluating on the PTB, ...  1610.03946v1   
16667  , but none of these methods can be applied dir...  1708.04033v1   
16668  , we use multiple long short-term memory  laye...  1708.04033v1   

          source_id  target_year  \
0       1409.3215v1         2016   
1       1412.7449v1         2016   
2      1506.03134v1         2016   
3       1310.4546v1         2015   
4       1310.4546v1         2017   
...             ...          ...   
16664   1306.5606v1         2013   
16665   1301.3781v1         2016   
16666  1606.02529v1         2016   
16667  1603.02199v1         2017   
16668   1312.5602v1         2017   

                                           target_author  \
0                                  robin jia;percy liang   
1                                  robin jia;percy liang   
2                                  robin jia;percy liang   
3       chuang ding;lei xie;jie yan;weini zhang;yang liu   
4      paul michel;abhilasha ravichander;shruti rijhwani   
...                                                  ...   
16664                                      lars kotthoff   
16665                       jessica ficler;yoav goldberg   
16666                       jessica ficler;yoav goldberg   
16667  tadanobu inoue;giovanni de magistris;asim muna...   
16668  tadanobu inoue;giovanni de magistris;asim muna...   

                                           source_author  
0                 ilya sutskever;oriol vinyals;quoc v le  
1      oriol vinyals;lukasz kaiser;terry koo;slav pet...  
2           oriol vinyals;meire fortunato;navdeep jaitly  
3      tomas mikolov;ilya sutskever;kai chen 0010;gre...  
4      tomas mikolov;ilya sutskever;kai chen 0010;gre...  
...                                                  ...  
16664  barry hurley;lars kotthoff;yuri malitsky;barry...  
16665   tomas mikolov;kai chen;greg corrado;jeffrey dean  
16666                       jessica ficler;yoav goldberg  
16667  sergey levine;peter pastor;alex krizhevsky;dei...  
16668  volodymyr mnih;koray kavukcuoglu;david silver;...  

[16669 rows x 7 columns]

In [34]:
df['#1 String'] = df['left_citated_text'].str[-128:]
df['#2 String'] = df['right_citated_text'].str[:128]
df

left_citated_text  \
0      We conducted additional experiments on artific...   
1      We conducted additional experiments on artific...   
2      Reproducibility. All code, data, and experimen...   
3      st like CWS and POS tagging, automatic prosody...   
4      We begin by considering a document as the set ...   
...                                                  ...   
16662  With human annotation of data, significant int...   
16663  An effective probabilistic approach to aggrega...   
16665  This approach works reasonably well, but does ...   
16667  Fig. 10 shows histograms of the execution time...   
16668  As we can see from Eq. , the target of the lea...   

                                      right_citated_text     target_id  \
0      andsyntactic parsing .Because RNNs make very f...  1606.03622v1   
1      .Because RNNs make very few domain-specific as...  1606.03622v1   
2      ; in a Pointer Network,the only way to generat...  1606.03622v1   
3      . Recently, nsur .  have shown superior perfor...  1511.00360v1   
4      model trained on the Google News dataset3.In a...  1705.10900v1   
...                                                  ...           ...   
16662  proposed a yesian EM framework for continuous-...  1503.06619v1   
16663  . as is defined as the inverse of accuracy: It...  1503.06619v1   
16665  on the POS sequences in PTB trainingset.The re...  1610.03946v1   
16667  , but none of these methods can be applied dir...  1708.04033v1   
16668  , we use multiple long short-term memory  laye...  1708.04033v1   

          source_id  target_year  \
0       1409.3215v1         2016   
1       1412.7449v1         2016   
2      1506.03134v1         2016   
3       1310.4546v1         2015   
4       1310.4546v1         2017   
...             ...          ...   
16662  1512.02393v1         2015   
16663  1512.02393v1         2015   
16665   1301.3781v1         2016   
16667  1603.02199v1         2017   
16668   1312.5602v1         2017   

                                           target_author  \
0                                  robin jia;percy liang   
1                                  robin jia;percy liang   
2                                  robin jia;percy liang   
3       chuang ding;lei xie;jie yan;weini zhang;yang liu   
4      paul michel;abhilasha ravichander;shruti rijhwani   
...                                                  ...   
16662  tingting zhu;nic dunkley;joachim behar;david a...   
16663  tingting zhu;nic dunkley;joachim behar;david a...   
16665                       jessica ficler;yoav goldberg   
16667  tadanobu inoue;giovanni de magistris;asim muna...   
16668  tadanobu inoue;giovanni de magistris;asim muna...   

                                           source_author  \
0                 ilya sutskever;oriol vinyals;quoc v le   
1      oriol vinyals;lukasz kaiser;terry koo;slav pet...   
2           oriol vinyals;meire fortunato;navdeep jaitly   
3      tomas mikolov;ilya sutskever;kai chen 0010;gre...   
4      tomas mikolov;ilya sutskever;kai chen 0010;gre...   
...                                                  ...   
16662                  changbo zhu;huan xu;shuicheng yan   
16663                  changbo zhu;huan xu;shuicheng yan   
16665   tomas mikolov;kai chen;greg corrado;jeffrey dean   
16667  sergey levine;peter pastor;alex krizhevsky;dei...   
16668  volodymyr mnih;koray kavukcuoglu;david silver;...   

                                               #1 String  \
0      le, recurrent neural networks  have made swift...   
1      networks  have made swift inroads intomany str...   
2      n-based copying can be seen as acombination of...   
3      sing neural networks from raw text in a fully ...   
4      s their usefulness for real-world tasks.As a f...   
...                                                  ...   
16662  ion of each expert annotator and the underlyin...   
16663  reduce annotator inter- and intra-variability....   
16665  ell in 

In [35]:
left_citated_text  = df['#1 String'].values.tolist()
right_citated_text = df['#2 String'].values.tolist()
total_citated_text = list(set(left_citated_text + right_citated_text))
citated_voca = {}
left_citated_id = []
right_citated_id = []
for i, v in enumerate(total_citated_text):
    citated_voca[v] = i
citated_voca

{'ameters for the text representation model. We take Jsemi as the loss function, and train neural networks with the Adam algorithm': 0,
 'ck-box attacks without a substitute model , based on the principle that adversarial examples can transfer among different models': 1,
 'vel models .Outside of language modeling, improvements have been reported on part-of-speech tagging  andnamed entity recognition': 2,
 ' models such as Deep Convolutional GAN  , undary Equilibrium GAN  , and the combination of DCGAN with a Variational Autoencoder ': 3,
 'by leveraging semantic denotations during structural search.Third, to train from weak supervision and directly maximize the expe': 4,
 'introduced a simplified version of LSTMs called Gated Recurrent Units  with has one less gate, and consequently fewer parameters': 5,
 '. Architectures employed for NLP applications differ in that they typically involve temporal ratherthan spatial convolutions.t C': 6,
 'explore the magnitude-based pruning in conjunc

In [36]:
for l, r in zip(df['#1 String'], df['#2 String']):
        left_citated_id.append(citated_voca[l])
        right_citated_id.append(citated_voca[r])

In [37]:
df['#1 ID'] = left_citated_id
df['#2 ID'] = right_citated_id

In [38]:
df

left_citated_text  \
0      We conducted additional experiments on artific...   
1      We conducted additional experiments on artific...   
2      Reproducibility. All code, data, and experimen...   
3      st like CWS and POS tagging, automatic prosody...   
4      We begin by considering a document as the set ...   
...                                                  ...   
16662  With human annotation of data, significant int...   
16663  An effective probabilistic approach to aggrega...   
16665  This approach works reasonably well, but does ...   
16667  Fig. 10 shows histograms of the execution time...   
16668  As we can see from Eq. , the target of the lea...   

                                      right_citated_text     target_id  \
0      andsyntactic parsing .Because RNNs make very f...  1606.03622v1   
1      .Because RNNs make very few domain-specific as...  1606.03622v1   
2      ; in a Pointer Network,the only way to generat...  1606.03622v1   
3      . Recently, nsur .  have shown superior perfor...  1511.00360v1   
4      model trained on the Google News dataset3.In a...  1705.10900v1   
...                                                  ...           ...   
16662  proposed a yesian EM framework for continuous-...  1503.06619v1   
16663  . as is defined as the inverse of accuracy: It...  1503.06619v1   
16665  on the POS sequences in PTB trainingset.The re...  1610.03946v1   
16667  , but none of these methods can be applied dir...  1708.04033v1   
16668  , we use multiple long short-term memory  laye...  1708.04033v1   

          source_id  target_year  \
0       1409.3215v1         2016   
1       1412.7449v1         2016   
2      1506.03134v1         2016   
3       1310.4546v1         2015   
4       1310.4546v1         2017   
...             ...          ...   
16662  1512.02393v1         2015   
16663  1512.02393v1         2015   
16665   1301.3781v1         2016   
16667  1603.02199v1         2017   
16668   1312.5602v1         2017   

                                           target_author  \
0                                  robin jia;percy liang   
1                                  robin jia;percy liang   
2                                  robin jia;percy liang   
3       chuang ding;lei xie;jie yan;weini zhang;yang liu   
4      paul michel;abhilasha ravichander;shruti rijhwani   
...                                                  ...   
16662  tingting zhu;nic dunkley;joachim behar;david a...   
16663  tingting zhu;nic dunkley;joachim behar;david a...   
16665                       jessica ficler;yoav goldberg   
16667  tadanobu inoue;giovanni de magistris;asim muna...   
16668  tadanobu inoue;giovanni de magistris;asim muna...   

                                           source_author  \
0                 ilya sutskever;oriol vinyals;quoc v le   
1      oriol vinyals;lukasz kaiser;terry koo;slav pet...   
2           oriol vinyals;meire fortunato;navdeep jaitly   
3      tomas mikolov;ilya sutskever;kai chen 0010;gre...   
4      tomas mikolov;ilya sutskever;kai chen 0010;gre...   
...                                                  ...   
16662                  changbo zhu;huan xu;shuicheng yan   
16663                  changbo zhu;huan xu;shuicheng yan   
16665   tomas mikolov;kai chen;greg corrado;jeffrey dean   
16667  sergey levine;peter pastor;alex krizhevsky;dei...   
16668  volodymyr mnih;koray kavukcuoglu;david silver;...   

                                               #1 String  \
0      le, recurrent neural networks  have made swift...   
1      networks  have made swift inroads intomany str...   
2      n-based copying can be seen as acombination of...   
3      sing neural networks from raw text in a fully ...   
4      s their usefulness for real-world tasks.As a f...   
...                                                  ...   
16662  ion of each expert annotator and the underlyin...   
16663  reduce annotator inter- and intra-variability....   
16665  ell in 

In [39]:
year = 2017
train_idx = df['target_year'][df['target_year'] < year].index
test_idx = df['target_year'][df['target_year'] >= year].index
train_df = df.loc[train_idx]
test_df = df.loc[test_idx]

In [40]:
test_df

left_citated_text  \
4      We begin by considering a document as the set ...   
5      With GMM and Aw2v+Ph, the F1-Score of clusteri...   
6      We evaluate our method on the CSP dataset8. Th...   
7      We perform document-level binary sentiment cla...   
8      In the lack of sufficient health status inform...   
...                                                  ...   
16649  We now demonstrate cascading modern CNN archit...   
16650  For the scattering transform we used J=2 which...   
16651  We now consider the popular CIFAR-10 dataset c...   
16667  Fig. 10 shows histograms of the execution time...   
16668  As we can see from Eq. , the target of the lea...   

                                      right_citated_text     target_id  \
4      model trained on the Google News dataset3.In a...  1705.10900v1   
5      . We observe that by themselves, Ph embeddings...  1705.10900v1   
6      . We observe that Ph embeddings perform poorly...  1705.10900v1   
7      or purely word vector based methods  . .cument...  1705.10900v1   
8      . Two most popular approaches of DGM rely on v...  1709.00845v1   
...                                                  ...           ...   
16649  , as a reference and construct a similar archi...  1703.08961v1   
16650  . Specifically we modify the WRN of 16 layers ...  1703.08961v1   
16651  . Table 3 reports the accuracy in the unsuperv...  1703.08961v1   
16667  , but none of these methods can be applied dir...  1708.04033v1   
16668  , we use multiple long short-term memory  laye...  1708.04033v1   

          source_id  target_year  \
4       1310.4546v1         2017   
5       1408.5882v1         2017   
6       1405.4053v1         2017   
7       1405.4053v1         2017   
8       1406.5298v1         2017   
...             ...          ...   
16649  1605.07146v1         2017   
16650  1605.07146v1         2017   
16651  1502.03167v1         2017   
16667  1603.02199v1         2017   
16668   1312.5602v1         2017   

                                           target_author  \
4      paul michel;abhilasha ravichander;shruti rijhwani   
5      paul michel;abhilasha ravichander;shruti rijhwani   
6      paul michel;abhilasha ravichander;shruti rijhwani   
7      paul michel;abhilasha ravichander;shruti rijhwani   
8      andre s yoon;taehoon lee;yongsub lim;deokwoo j...   
...                                                  ...   
16649  edouard oyallon;eugene belilovsky;sergey zagor...   
16650  edouard oyallon;eugene belilovsky;sergey zagor...   
16651  edouard oyallon;eugene belilovsky;sergey zagor...   
16667  tadanobu inoue;giovanni de magistris;asim muna...   
16668  tadanobu inoue;giovanni de magistris;asim muna...   

                                           source_author  \
4      tomas mikolov;ilya sutskever;kai chen 0010;gre...   
5                                               yoon kim   
6                                quoc v le;tomas mikolov   
7                                quoc v le;tomas mikolov   
8      diederik p kingma;shakir mohamed;danilo jimene...   
...                                                  ...   
16649                   sergey zagoruyko;nikos komodakis   
16650                   sergey zagoruyko;nikos komodakis   
16651                     sergey ioffe;christian szegedy   
16667  sergey levine;peter pastor;alex krizhevsky;dei...   
16668  volodymyr mnih;koray kavukcuoglu;david silver;...   

                                               #1 String  \
4      s their usefulness for real-world tasks.As a f...   
5      presented in Table 1. For comparison, we provi...   
6      e word vectors in that sentence. The results a...   
7      d recent attention owing to their utility in s...   
8      enerative models  have recently achieved state...   
...                                                  ...   
16649  ication task. re we consider cascading the sca...   
16650  on CIFAR-10, all based on end-to-end learned C...   
16651  on in b

In [41]:
bert_column = ['Quality', '#1 ID', '#2 ID', '#1 String', '#2 String', 'target_id', 'source_author']

In [42]:
from sklearn import preprocessing
lb = preprocessing.LabelBinarizer()
lb.fit_transform(df['source_id'].values)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [43]:
lb.get_params()

{'neg_label': 0, 'pos_label': 1, 'sparse_output': False}

In [44]:
def convert_argmax(df, lb):

    y = df['source_id'].values
    y = lb.transform(y)
    y = np.argmax(y, axis=1)
    df['Quality'] = y

    return df

In [45]:
train_df1 = convert_argmax(train_df, lb)

In [46]:
train_df1

left_citated_text  \
0      We conducted additional experiments on artific...   
1      We conducted additional experiments on artific...   
2      Reproducibility. All code, data, and experimen...   
3      st like CWS and POS tagging, automatic prosody...   
13     stillation has been traditionally applied to n...   
...                                                  ...   
16660  An important inspiration for the proposed fram...   
16661  The proposal made here also owes a lot to the ...   
16662  With human annotation of data, significant int...   
16663  An effective probabilistic approach to aggrega...   
16665  This approach works reasonably well, but does ...   

                                      right_citated_text     target_id  \
0      andsyntactic parsing .Because RNNs make very f...  1606.03622v1   
1      .Because RNNs make very few domain-specific as...  1606.03622v1   
2      ; in a Pointer Network,the only way to generat...  1606.03622v1   
3      . Recently, nsur .  have shown superior perfor...  1511.00360v1   
13     usedcompression to transfer knowledge from a d...  1511.06295v1   
...                                                  ...           ...   
16660  . Two important differenceswith the approach p...  1502.04156v1   
16661   and generativeadversarial networks ( ., 2014)...  1502.04156v1   
16662  proposed a yesian EM framework for continuous-...  1503.06619v1   
16663  . as is defined as the inverse of accuracy: It...  1503.06619v1   
16665  on the POS sequences in PTB trainingset.The re...  1610.03946v1   

          source_id  target_year  \
0       1409.3215v1         2016   
1       1412.7449v1         2016   
2      1506.03134v1         2016   
3       1310.4546v1         2015   
13      1312.6184v1         2015   
...             ...          ...   
16660   1406.2751v1         2015   
16661   1306.1091v1         2015   
16662  1512.02393v1         2015   
16663  1512.02393v1         2015   
16665   1301.3781v1         2016   

                                           target_author  \
0                                  robin jia;percy liang   
1                                  robin jia;percy liang   
2                                  robin jia;percy liang   
3       chuang ding;lei xie;jie yan;weini zhang;yang liu   
13     andrei a rusu;sergio gomez colmenarejo;caglar ...   
...                                                  ...   
16660  yoshua bengio;dong-hyun lee;jorg bornschein;th...   
16661  yoshua bengio;dong-hyun lee;jorg bornschein;th...   
16662  tingting zhu;nic dunkley;joachim behar;david a...   
16663  tingting zhu;nic dunkley;joachim behar;david a...   
16665                       jessica ficler;yoav goldberg   

                                           source_author  \
0                 ilya sutskever;oriol vinyals;quoc v le   
1      oriol vinyals;lukasz kaiser;terry koo;slav pet...   
2           oriol vinyals;meire fortunato;navdeep jaitly   
3      tomas mikolov;ilya sutskever;kai chen 0010;gre...   
13                                 jimmy ba;rich caruana   
...                                                  ...   
16660                    j\"org bornschein;yoshua bengio   
16661  yoshua bengio;eric laufer;guillaume alain;jaso...   
16662                  changbo zhu;huan xu;shuicheng yan   
16663                  changbo zhu;huan xu;shuicheng yan   
16665   tomas mikolov;kai chen;greg corrado;jeffrey dean   

                                               #1 String  \
0      le, recurrent neural networks  have made swift...   
1      networks  have made swift inroads intomany str...   
2      n-based copying can be seen as acombination of...   
3      sing neural networks from raw text in a fully ...   
13      by cila . , whoproposed it as a means of comp...   
...                                                  ...   
16660  lgorithm  and which finds very interesting ins...   
16661  about the same or better as was obtained for c...   
16662  ion of 

In [48]:
anArray = train_df1['Quality'].values

In [116]:
test_df1 = convert_argmax(test_df, lb)

In [117]:
test_df1

left_citated_text  \
4      We begin by considering a document as the set ...   
5      With GMM and Aw2v+Ph, the F1-Score of clusteri...   
6      We evaluate our method on the CSP dataset8. Th...   
7      We perform document-level binary sentiment cla...   
8      In the lack of sufficient health status inform...   
...                                                  ...   
16649  We now demonstrate cascading modern CNN archit...   
16650  For the scattering transform we used J=2 which...   
16651  We now consider the popular CIFAR-10 dataset c...   
16667  Fig. 10 shows histograms of the execution time...   
16668  As we can see from Eq. , the target of the lea...   

                                      right_citated_text     target_id  \
4      model trained on the Google News dataset3.In a...  1705.10900v1   
5      . We observe that by themselves, Ph embeddings...  1705.10900v1   
6      . We observe that Ph embeddings perform poorly...  1705.10900v1   
7      or purely word vector based methods  . .cument...  1705.10900v1   
8      . Two most popular approaches of DGM rely on v...  1709.00845v1   
...                                                  ...           ...   
16649  , as a reference and construct a similar archi...  1703.08961v1   
16650  . Specifically we modify the WRN of 16 layers ...  1703.08961v1   
16651  . Table 3 reports the accuracy in the unsuperv...  1703.08961v1   
16667  , but none of these methods can be applied dir...  1708.04033v1   
16668  , we use multiple long short-term memory  laye...  1708.04033v1   

          source_id  target_year  \
4       1310.4546v1         2017   
5       1408.5882v1         2017   
6       1405.4053v1         2017   
7       1405.4053v1         2017   
8       1406.5298v1         2017   
...             ...          ...   
16649  1605.07146v1         2017   
16650  1605.07146v1         2017   
16651  1502.03167v1         2017   
16667  1603.02199v1         2017   
16668   1312.5602v1         2017   

                                           target_author  \
4      paul michel;abhilasha ravichander;shruti rijhwani   
5      paul michel;abhilasha ravichander;shruti rijhwani   
6      paul michel;abhilasha ravichander;shruti rijhwani   
7      paul michel;abhilasha ravichander;shruti rijhwani   
8      andre s yoon;taehoon lee;yongsub lim;deokwoo j...   
...                                                  ...   
16649  edouard oyallon;eugene belilovsky;sergey zagor...   
16650  edouard oyallon;eugene belilovsky;sergey zagor...   
16651  edouard oyallon;eugene belilovsky;sergey zagor...   
16667  tadanobu inoue;giovanni de magistris;asim muna...   
16668  tadanobu inoue;giovanni de magistris;asim muna...   

                                           source_author  \
4      tomas mikolov;ilya sutskever;kai chen 0010;gre...   
5                                               yoon kim   
6                                quoc v le;tomas mikolov   
7                                quoc v le;tomas mikolov   
8      diederik p kingma;shakir mohamed;danilo jimene...   
...                                                  ...   
16649                   sergey zagoruyko;nikos komodakis   
16650                   sergey zagoruyko;nikos komodakis   
16651                     sergey ioffe;christian szegedy   
16667  sergey levine;peter pastor;alex krizhevsky;dei...   
16668  volodymyr mnih;koray kavukcuoglu;david silver;...   

                                               #1 String  \
4      s their usefulness for real-world tasks.As a f...   
5      presented in Table 1. For comparison, we provi...   
6      e word vectors in that sentence. The results a...   
7      d recent attention owing to their utility in s...   
8      enerative models  have recently achieved state...   
...                                                  ...   
16649  ication task. re we consider cascading the sca...   
16650  on CIFAR-10, all based on end-to-end learned C...   
16651  on in b

In [118]:
train_df, test_df = train_df1[bert_column], test_df1[bert_column]

In [119]:
test_df

Quality  #1 ID  #2 ID  \
4           90  23427  10153   
5          136  13225    377   
6          120  15416   1612   
7          120  12091  22025   
8          130   9400  16385   
...        ...    ...    ...   
16649      397  11129   1356   
16650      397  13604   7143   
16651      185   2229   1423   
16667      357  20485  21074   
16668       99   1391  22959   

                                               #1 String  \
4      s their usefulness for real-world tasks.As a f...   
5      presented in Table 1. For comparison, we provi...   
6      e word vectors in that sentence. The results a...   
7      d recent attention owing to their utility in s...   
8      enerative models  have recently achieved state...   
...                                                  ...   
16649  ication task. re we consider cascading the sca...   
16650  on CIFAR-10, all based on end-to-end learned C...   
16651  on in both case. We utilize batch normalizatio...   
16667  l concept is shown in Fig. 1.Recent studies ha...   
16668  work decision.Algorithm 2 shows the learning t...   

                                               #2 String     target_id  \
4      model trained on the Google News dataset3.In a...  1705.10900v1   
5      . We observe that by themselves, Ph embeddings...  1705.10900v1   
6      . We observe that Ph embeddings perform poorly...  1705.10900v1   
7      or purely word vector based methods  . .cument...  1705.10900v1   
8      . Two most popular approaches of DGM rely on v...  1709.00845v1   
...                                                  ...           ...   
16649  , as a reference and construct a similar archi...  1703.08961v1   
16650  . Specifically we modify the WRN of 16 layers ...  1703.08961v1   
16651  . Table 3 reports the accuracy in the unsuperv...  1703.08961v1   
16667  , but none of these methods can be applied dir...  1708.04033v1   
16668  , we use multiple long short-term memory  laye...  1708.04033v1   

                                           source_author  
4      tomas mikolov;ilya sutskever;kai chen 0010;gre...  
5                                               yoon kim  
6                                quoc v le;tomas mikolov  
7                                quoc v le;tomas mikolov  
8      diederik p kingma;shakir mohamed;danilo jimene...  
...                                                  ...  
16649                   sergey zagoruyko;nikos komodakis  
16650                   sergey zagoruyko;nikos komodakis  
16651                     sergey ioffe;christian szegedy  
16667  sergey levine;peter pastor;alex krizhevsky;dei...  
16668  volodymyr mnih;koray kavukcuoglu;david silver;...  

[4783 rows x 7 columns]

In [120]:
train_df

Quality  #1 ID  #2 ID  \
0          139   8103   7582   
1          174    818  21392   
2          232  10444   2237   
3           90   5440  14282   
13         102   7301   3444   
...        ...    ...    ...   
16660      127  19965  15181   
16661       80   1787  20657   
16662      319   6892    723   
16663      319  20408  15313   
16665       69   2953   4794   

                                               #1 String  \
0      le, recurrent neural networks  have made swift...   
1      networks  have made swift inroads intomany str...   
2      n-based copying can be seen as acombination of...   
3      sing neural networks from raw text in a fully ...   
13      by cila . , whoproposed it as a means of comp...   
...                                                  ...   
16660  lgorithm  and which finds very interesting ins...   
16661  about the same or better as was obtained for c...   
16662  ion of each expert annotator and the underlyin...   
16663  reduce annotator inter- and intra-variability....   
16665  ell in the CKY chart.3In both approaches,the P...   

                                               #2 String     target_id  \
0      andsyntactic parsing .Because RNNs make very f...  1606.03622v1   
1      .Because RNNs make very few domain-specific as...  1606.03622v1   
2      ; in a Pointer Network,the only way to generat...  1606.03622v1   
3      . Recently, nsur .  have shown superior perfor...  1511.00360v1   
13     usedcompression to transfer knowledge from a d...  1511.06295v1   
...                                                  ...           ...   
16660  . Two important differenceswith the approach p...  1502.04156v1   
16661   and generativeadversarial networks ( ., 2014)...  1502.04156v1   
16662  proposed a yesian EM framework for continuous-...  1503.06619v1   
16663  . as is defined as the inverse of accuracy: It...  1503.06619v1   
16665  on the POS sequences in PTB trainingset.The re...  1610.03946v1   

                                           source_author  
0                 ilya sutskever;oriol vinyals;quoc v le  
1      oriol vinyals;lukasz kaiser;terry koo;slav pet...  
2           oriol vinyals;meire fortunato;navdeep jaitly  
3      tomas mikolov;ilya sutskever;kai chen 0010;gre...  
13                                 jimmy ba;rich caruana  
...                                                  ...  
16660                    j\"org bornschein;yoshua bengio  
16661  yoshua bengio;eric laufer;guillaume alain;jaso...  
16662                  changbo zhu;huan xu;shuicheng yan  
16663                  changbo zhu;huan xu;shuicheng yan  
16665   tomas mikolov;kai chen;greg corrado;jeffrey dean  

[7447 rows x 7 columns]

In [ ]:
train_df.loc[train_df['#1 ID'] == 14050]

In [ ]:
temp_df = test_df

In [ ]:
temp_df.reset_index()

In [ ]:
multi_label_info = []
for i in temp_df.groupby(['#1 ID', '#2 ID']):
    instance_label = {}
    instance_label['Quality'] = i[1]['Quality'].values
    instance_label['index'] = i[1]['Quality'].index.values
    multi_label_info.append(instance_label)

In [ ]:
for i in range (0,len(multi_label_info)):
    if multi_label_info[i]['index'].any() == 0:
        print(multi_label_info[i])
        print(i)

In [ ]:
multi_label_info[0]['index']

In [ ]:
import tensorflow as tf
print("Num GPUs Available: HI ", len(tf.config.experimental.list_physical_devices('GPU')))

### Preprocessing

In [1]:
import pandas as pd
import transformers
import torch
import tqdm

In [2]:
tokenizer = transformers.BertTokenizer.from_pretrained("bert-base-uncased", do_lower_case=True)

In [3]:
a = tokenizer.encode_plus("Hi. How are you?","Hi. I am fine and how are you?", add_special_tokens = True, max_length = 100, padding="max_length")

In [254]:
b = tokenizer.encode_plus("Hi. I am fine and how are you?", None, add_special_tokens = True, max_length = 100, padding=True)

In [5]:
len(a["input_ids"])

100

In [6]:
a["input_ids"]

[101,
 7632,
 1012,
 2129,
 2024,
 2017,
 1029,
 102,
 7632,
 1012,
 1045,
 2572,
 2986,
 1998,
 2129,
 2024,
 2017,
 1029,
 102,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [10]:
tokenizer.cls_token, tokenizer.cls_token_id

('[CLS]', 101)

In [15]:
context = "You are using pip version.Just like a watched pot never boils"
print(" ".join(context.split()))

You are using pip version.Just like a watched pot never boils


In [20]:
dataFile["right_citated_text"].values[0]

"andsyntactic parsing .Because RNNs make very few domain-specific assumptions,they have the potential to succeed at a wide variety of taskswith minimal feature engineering.wever, this flexibility also puts RNNs at a disadvantage compared tostandard semantic parsers, which can generalize naturallyby leveraging their built-in awareness of logical compositionality.In this paper, we introduce data recombination,a generic framework for declaratively injecting prior knowledgeinto a domain-general structured prediction model.In data recombination, prior knowledge about a taskis used to build a high-precision generative modelthat expands the empirical distributionby allowing fragments of different examples to be combined inparticular ways.mples from this generative model are then used to train a domain-general model.In the case of semantic parsing, we construct a generative modelby inducing a synchronous context-free grammar ,creating new examples such as those shown in Figure 1;our domain-gen

In [ ]:
def get_gcn_data(train_df, test_df, save_dir):
    with open('{}/gcn_pretrain.pkl'.format(save_dir), 'rb') as f:
        embedding = pickle.load(f)
        node2id = pickle.load(f)
    gcn_train = np.array([[node2id[i]] for i in train_df['query_id'].values])
    gcn_test = np.array([[node2id[i]] for i in test_df['query_id'].values])
    return gcn_train, gcn_test, embedding

In [92]:
embedding = None
node2id = None
with open('/mnt/e/MS/2-1B/AP-FIR/bert-gcn/pre_train/gcn/PeerRead/PeerRead_gcn_pretrain_author.pkl', 'rb') as f:
        embedding = pickle.load(f)
        node2id = pickle.load(f)

In [91]:
import pickle

In [95]:
len(embedding[0])

768

In [130]:
train_df['source_author'].values[0].split(';')[-1]

'quoc v le'

In [131]:
arr = train_df['source_author'].values

In [189]:
cnt = 0
for i in arr:
    cnt += 1
    if i.split(';')[-1] == 'afroze ibrahim baqapuri':
        print('Teri maa ki ', cnt)
    

Teri maa ki  1111
Teri maa ki  1112
Teri maa ki  1264
Teri maa ki  1265
Teri maa ki  1266
Teri maa ki  1267
Teri maa ki  1358
Teri maa ki  1359
Teri maa ki  1360
Teri maa ki  1361
Teri maa ki  2168
Teri maa ki  2169
Teri maa ki  2698
Teri maa ki  2840
Teri maa ki  2850
Teri maa ki  3943
Teri maa ki  4738
Teri maa ki  5316
Teri maa ki  5317
Teri maa ki  5318
Teri maa ki  5430
Teri maa ki  6831


In [185]:
node2id['afroze ibrahim baqapuri']

KeyError: 'afroze ibrahim baqapuri'

In [139]:
embedding[3564]

array([-4.75661084e-02, -2.11767226e-01, -7.69936517e-02, -1.34367093e-01,
       -1.32247269e-01,  9.25423503e-02, -1.23237289e-01, -2.50031084e-01,
        1.83598384e-01, -1.87942892e-01,  1.05373263e-02, -3.16464901e-03,
        2.89688170e-01,  1.16193756e-01,  3.08152884e-02, -1.64103135e-01,
        3.85200605e-02,  1.93548799e-02,  1.04115993e-01,  1.59260869e-01,
        3.75042222e-02, -4.13777083e-01, -1.40298188e-01, -7.97704756e-02,
        1.69954151e-02,  9.29089710e-02,  5.71189970e-02, -9.63231102e-02,
        2.62236208e-01,  2.40637809e-02,  1.57377809e-01, -1.58616498e-01,
       -1.79514438e-01,  1.06614847e-02, -4.85762879e-02,  8.04453343e-02,
       -7.72103742e-02, -1.38636418e-02, -5.83091676e-02,  3.78895551e-03,
       -1.35671839e-01,  8.73243362e-02, -8.78408253e-02,  7.90649429e-02,
        3.46747875e-01,  2.61593997e-01,  1.78148653e-02, -1.58512473e-01,
        2.26705939e-01, -1.97524950e-01,  2.39470914e-01, -1.20129056e-01,
        3.78371663e-02,  

In [208]:
gcn_train = np.zeros(shape=(1,768))

In [209]:
b = np.append(gcn_train, [embedding[node2id[arr[0].split(';')[-1]]]], axis=0)
b = np.append(b, [embedding[node2id[arr[1].split(';')[-1]]]], axis=0)
b = np.append(b, [embedding[node2id[arr[2].split(';')[-1]]]], axis=0)

In [211]:
len(b)

4

In [191]:
node2id['afroze ibrahim baqapuri'] 

KeyError: 'afroze ibrahim baqapuri'

In [197]:
x = zip([1,2], [9,10], [])

In [198]:
list(x)

[]

In [212]:
loss = nn.CrossEntropyLoss()

In [213]:
input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
output = loss(input, target)

In [216]:
output

tensor(2.2013, grad_fn=<NllLossBackward>)

In [215]:
output.backward()

In [218]:
target.shape[0]

3

In [245]:
targetMatrix = np.zeros(shape=(10, 3))
targets = np.array([0,2,2,1,0,2,1,1,0,0])

In [247]:
for i in range(0,targets.shape[0]):
    print(i, targets[[i]])
    targetMatrix[i,targets[[i]]] = 1

0 [0]
1 [2]
2 [2]
3 [1]
4 [0]
5 [2]
6 [1]
7 [1]
8 [0]
9 [0]


In [248]:
targetMatrix

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [239]:
targets

array([[0, 2, 2, 1, 0, 2, 1, 1, 0, 0]])

In [271]:
a = ('MM', ['hi', 'bye'], 'MM')

In [272]:
type(a)

tuple

In [273]:
a

('MM', ['hi', 'bye'], 'MM')

In [274]:
x = torch.randn(10, 5)
y = torch.randint(5, (10,))

In [275]:
x

tensor([[-0.6558, -0.6311, -1.1523, -0.4526, -0.1082],
        [-0.0242,  0.2569,  1.0637, -1.3420,  0.7725],
        [-1.3376,  0.0537, -0.2791, -1.9397,  0.3444],
        [-0.7768, -0.5065,  0.4023,  0.4000,  1.2417],
        [ 0.8871,  0.8222,  1.1341,  0.0854, -0.6681],
        [ 1.4926, -1.0424, -0.1974, -1.4365,  2.7164],
        [ 0.4590,  1.7561, -0.7182, -0.6271, -0.7176],
        [-0.5132,  1.5448,  1.0711,  0.4586,  0.7220],
        [-0.3532,  0.9306,  0.5386, -1.3265, -1.6723],
        [ 1.5191,  0.5804,  0.7835,  1.4071,  0.4309]])

In [279]:
y

tensor([4, 4, 1, 2, 3, 0, 3, 4, 3, 1])

In [280]:
loss = nn.CrossEntropyLoss()(x, y)

In [281]:
loss

tensor(1.8631)

In [10]:
import torch
outputs = torch.randn(10,10)

In [15]:
outputs.cpu().detach().numpy()

array([[ 1.5141089 ,  0.21601109,  0.3352844 , -0.47060046,  0.52831715,
         0.8986401 , -1.3377849 , -0.21681648,  0.3495095 ,  0.04451937],
       [ 0.82896525, -0.43477282, -0.6625765 , -1.1890138 ,  1.5161456 ,
         0.7036071 ,  0.09192441,  0.15651953,  0.834813  ,  0.8876868 ],
       [-1.6549444 ,  0.4601838 , -0.8080143 , -1.2026032 , -0.7485504 ,
        -0.01099867, -0.15947303,  1.3419424 , -0.48343274, -1.5495147 ],
       [-0.38402694,  0.20689583,  1.091941  ,  0.8155733 , -0.90273005,
         0.06526163,  1.5922868 , -0.741216  , -0.12303007,  0.14203379],
       [ 0.80925745, -0.8369664 ,  0.69213337,  0.41236097,  0.049534  ,
        -1.89061   , -1.6556381 , -0.33929276, -0.18388875,  0.22856106],
       [ 0.87471455,  0.5971452 ,  1.2274413 ,  0.62335396,  0.16428806,
         0.7154189 , -0.5671112 , -1.0328497 ,  0.64456457,  0.32417497],
       [ 0.35605755,  1.5302416 ,  0.04111671, -0.32558602, -1.2731838 ,
        -0.6747714 ,  1.0610003 ,  1.7816477 

In [17]:
temp = outputs.cpu().detach().numpy().tolist()

In [19]:
import scipy.stats as ss

In [23]:
ss.rankdata(temp[0])

array([10.,  5.,  6.,  2.,  8.,  9.,  1.,  3.,  7.,  4.])

In [26]:
strr = 'Ashish'
final = 'Hi '+strr

In [27]:
final

'Hi Ashish'

In [56]:
for i in range(0,len(anArray)):
    if (anArray[i]).size > 1:
        print(anArray[i])

In [77]:
import numpy as np
from sklearn.metrics import average_precision_score
y_true = np.array([[0,0,0,1], [1,0,0,0], [0,0,1,0], [0,1,0,0]])
y_scores = np.array([[0.2, 0.4, 0.1, 0.3],[0.2, 0.4, 0.1, 0.3],[0.2, 0.4, 0.1, 0.3],[0.2, 0.4, 0.1, 0.3]])
average_precision_score(y_true, y_scores)

0.25

In [78]:
y_scores.shape

(4, 4)

In [79]:
lol = np.zeros(y_scores.shape)

In [80]:
lol

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

SyntaxError: invalid syntax (<ipython-input-81-4ea62681798a>, line 1)

In [24]:
from numpy import genfromtxt
from collections import defaultdict, Counter

In [21]:
dummyFile = './../../bert-gcn/dummy.txt'
y_trueFile = './../../bert-gcn/YTrue.csv'
predicFile = './../../bert-gcn/label_predictions.csv'

In [12]:
dummy = []
with open(dummyFile) as f:
    file = f.readlines()
    for eachElem in file:
        dummy.append(eachElem.strip())

In [19]:
y_true = genfromtxt(y_trueFile, delimiter=',')

In [22]:
predic = genfromtxt(predicFile, delimiter=',')

In [25]:
user_est_true = defaultdict(list)
for uid, true_r, est in zip(dummy, y_true, predic):
        user_est_true[uid].append((est, true_r))

In [44]:
precisions = dict()
recalls = dict()
threshold = 0.000001
k=5

In [48]:
for uid, user_ratings in user_est_true.items():
    print("uid: ",uid)
    n_rel = len(user_ratings[0][1][user_ratings[0][1] >= threshold])
    print(n_rel)
    n_rec_k = len(user_ratings[0][0][user_ratings[0][0] >= threshold])
    print("n_rec_k: ",n_rec_k)
    true_value = user_ratings[0][1]
    # print("true_value: ",true_value)
    true_index = true_value.argsort()[::-1]
    # print("true_index: ",true_index)
    true_k = list(filter(lambda i: true_value[i] > threshold, true_index))[:k]
    print("true_k: ",true_k)
    est_value = user_ratings[0][0]
    #print("est_value: ",est_value)
    est_index = est_value.argsort()[::-1]
    #print("est_index: ",est_index)
    est_k = list(filter(lambda i: est_value[i] > threshold, est_index))[:k]
    print("est_k: ",est_k)
    count_value = Counter(true_k + est_k)
    print("count_value: ",count_value)
    n_rel_and_rec_k = list(count_value.values()).count(2)
    print("n_rel_and_rec_k: ",n_rel_and_rec_k)
    precisions[uid] = n_rel_and_rec_k / n_rec_k if n_rec_k != 0 else 1
    recalls[uid] = n_rel_and_rec_k / n_rel if n_rel != 0 else 1
    

uid:  0
1
n_rec_k:  489
true_k:  [456]
est_k:  [108, 84, 28, 77, 35]
count_value:  Counter({456: 1, 108: 1, 84: 1, 28: 1, 77: 1, 35: 1})
n_rel_and_rec_k:  0
uid:  1
1
n_rec_k:  489
true_k:  [363]
est_k:  [215, 260, 363, 239, 329]
count_value:  Counter({363: 2, 215: 1, 260: 1, 239: 1, 329: 1})
n_rel_and_rec_k:  1
uid:  2
1
n_rec_k:  489
true_k:  [248]
est_k:  [88, 261, 333, 98, 315]
count_value:  Counter({248: 1, 88: 1, 261: 1, 333: 1, 98: 1, 315: 1})
n_rel_and_rec_k:  0
uid:  3
1
n_rec_k:  489
true_k:  [428]
est_k:  [303, 24, 103, 75, 387]
count_value:  Counter({428: 1, 303: 1, 24: 1, 103: 1, 75: 1, 387: 1})
n_rel_and_rec_k:  0
uid:  4
1
n_rec_k:  489
true_k:  [264]
est_k:  [264, 189, 356, 405, 139]
count_value:  Counter({264: 2, 189: 1, 356: 1, 405: 1, 139: 1})
n_rel_and_rec_k:  1
uid:  5
1
n_rec_k:  489
true_k:  [305]
est_k:  [36, 144, 148, 230, 102]
count_value:  Counter({305: 1, 36: 1, 144: 1, 148: 1, 230: 1, 102: 1})
n_rel_and_rec_k:  0
uid:  6
1
n_rec_k:  489
true_k:  [227]
est_k

true_k:  [254]
est_k:  [136, 174, 270, 139, 12]
count_value:  Counter({254: 1, 136: 1, 174: 1, 270: 1, 139: 1, 12: 1})
n_rel_and_rec_k:  0
uid:  75
1
n_rec_k:  462
true_k:  [90]
est_k:  [69, 90, 12, 120, 136]
count_value:  Counter({90: 2, 69: 1, 12: 1, 120: 1, 136: 1})
n_rel_and_rec_k:  1
uid:  76
1
n_rec_k:  489
true_k:  [307]
est_k:  [307, 332, 155, 112, 118]
count_value:  Counter({307: 2, 332: 1, 155: 1, 112: 1, 118: 1})
n_rel_and_rec_k:  1
uid:  77
1
n_rec_k:  489
true_k:  [371]
est_k:  [215, 194, 228, 242, 5]
count_value:  Counter({371: 1, 215: 1, 194: 1, 228: 1, 242: 1, 5: 1})
n_rel_and_rec_k:  0
uid:  78
1
n_rec_k:  489
true_k:  [58]
est_k:  [58, 1, 170, 126, 486]
count_value:  Counter({58: 2, 1: 1, 170: 1, 126: 1, 486: 1})
n_rel_and_rec_k:  1
uid:  79
1
n_rec_k:  489
true_k:  [207]
est_k:  [139, 270, 264, 190, 199]
count_value:  Counter({207: 1, 139: 1, 270: 1, 264: 1, 190: 1, 199: 1})
n_rel_and_rec_k:  0
uid:  80
1
n_rec_k:  489
true_k:  [428]
est_k:  [107, 92, 80, 75, 334]
co

true_k:  [139]
est_k:  [139, 123, 88, 155, 264]
count_value:  Counter({139: 2, 123: 1, 88: 1, 155: 1, 264: 1})
n_rel_and_rec_k:  1
uid:  145
1
n_rec_k:  489
true_k:  [66]
est_k:  [90, 23, 12, 66, 69]
count_value:  Counter({66: 2, 90: 1, 23: 1, 12: 1, 69: 1})
n_rel_and_rec_k:  1
uid:  146
1
n_rec_k:  489
true_k:  [88]
est_k:  [268, 260, 262, 215, 351]
count_value:  Counter({88: 1, 268: 1, 260: 1, 262: 1, 215: 1, 351: 1})
n_rel_and_rec_k:  0
uid:  147
1
n_rec_k:  489
true_k:  [39]
est_k:  [15, 11, 133, 158, 34]
count_value:  Counter({39: 1, 15: 1, 11: 1, 133: 1, 158: 1, 34: 1})
n_rel_and_rec_k:  0
uid:  148
1
n_rec_k:  487
true_k:  [269]
est_k:  [139, 264, 123, 190, 189]
count_value:  Counter({269: 1, 139: 1, 264: 1, 123: 1, 190: 1, 189: 1})
n_rel_and_rec_k:  0
uid:  149
1
n_rec_k:  489
true_k:  [103]
est_k:  [103, 80, 303, 75, 7]
count_value:  Counter({103: 2, 80: 1, 303: 1, 75: 1, 7: 1})
n_rel_and_rec_k:  1
uid:  150
1
n_rec_k:  489
true_k:  [78]
est_k:  [78, 116, 100, 205, 142]
count_

true_k:  [171]
est_k:  [36, 171, 8, 111, 336]
count_value:  Counter({171: 2, 36: 1, 8: 1, 111: 1, 336: 1})
n_rel_and_rec_k:  1
uid:  215
1
n_rec_k:  489
true_k:  [354]
est_k:  [354, 211, 351, 273, 322]
count_value:  Counter({354: 2, 211: 1, 351: 1, 273: 1, 322: 1})
n_rel_and_rec_k:  1
uid:  216
1
n_rec_k:  489
true_k:  [215]
est_k:  [215, 194, 228, 192, 262]
count_value:  Counter({215: 2, 194: 1, 228: 1, 192: 1, 262: 1})
n_rel_and_rec_k:  1
uid:  217
1
n_rec_k:  453
true_k:  [90]
est_k:  [90, 69, 12, 207, 124]
count_value:  Counter({90: 2, 69: 1, 12: 1, 207: 1, 124: 1})
n_rel_and_rec_k:  1
uid:  218
1
n_rec_k:  489
true_k:  [88]
est_k:  [88, 139, 155, 290, 123]
count_value:  Counter({88: 2, 139: 1, 155: 1, 290: 1, 123: 1})
n_rel_and_rec_k:  1
uid:  219
1
n_rec_k:  489
true_k:  [306]
est_k:  [276, 306, 99, 201, 100]
count_value:  Counter({306: 2, 276: 1, 99: 1, 201: 1, 100: 1})
n_rel_and_rec_k:  1
uid:  220
1
n_rec_k:  489
true_k:  [215]
est_k:  [215, 194, 228, 192, 174]
count_value:  C

est_k:  [69, 120, 136, 90, 273]
count_value:  Counter({117: 1, 69: 1, 120: 1, 136: 1, 90: 1, 273: 1})
n_rel_and_rec_k:  0
uid:  283
1
n_rec_k:  489
true_k:  [190]
est_k:  [290, 103, 192, 173, 136]
count_value:  Counter({190: 1, 290: 1, 103: 1, 192: 1, 173: 1, 136: 1})
n_rel_and_rec_k:  0
uid:  284
1
n_rec_k:  489
true_k:  [68]
est_k:  [278, 117, 136, 199, 245]
count_value:  Counter({68: 1, 278: 1, 117: 1, 136: 1, 199: 1, 245: 1})
n_rel_and_rec_k:  0
uid:  285
1
n_rec_k:  489
true_k:  [107]
est_k:  [67, 73, 39, 116, 107]
count_value:  Counter({107: 2, 67: 1, 73: 1, 39: 1, 116: 1})
n_rel_and_rec_k:  1
uid:  286
1
n_rec_k:  489
true_k:  [264]
est_k:  [262, 268, 269, 96, 273]
count_value:  Counter({264: 1, 262: 1, 268: 1, 269: 1, 96: 1, 273: 1})
n_rel_and_rec_k:  0
uid:  287
1
n_rec_k:  489
true_k:  [186]
est_k:  [157, 235, 150, 173, 166]
count_value:  Counter({186: 1, 157: 1, 235: 1, 150: 1, 173: 1, 166: 1})
n_rel_and_rec_k:  0
uid:  288
1
n_rec_k:  392
true_k:  [90]
est_k:  [90, 69, 207,

est_k:  [171, 111, 8, 336, 64]
count_value:  Counter({171: 2, 111: 1, 8: 1, 336: 1, 64: 1})
n_rel_and_rec_k:  1
uid:  351
1
n_rec_k:  489
true_k:  [148]
est_k:  [148, 168, 321, 159, 103]
count_value:  Counter({148: 2, 168: 1, 321: 1, 159: 1, 103: 1})
n_rel_and_rec_k:  1
uid:  352
1
n_rec_k:  489
true_k:  [406]
est_k:  [36, 426, 141, 132, 68]
count_value:  Counter({406: 1, 36: 1, 426: 1, 141: 1, 132: 1, 68: 1})
n_rel_and_rec_k:  0
uid:  353
1
n_rec_k:  489
true_k:  [120]
est_k:  [120, 136, 149, 69, 218]
count_value:  Counter({120: 2, 136: 1, 149: 1, 69: 1, 218: 1})
n_rel_and_rec_k:  1
uid:  354
1
n_rec_k:  489
true_k:  [273]
est_k:  [268, 273, 262, 260, 338]
count_value:  Counter({273: 2, 268: 1, 262: 1, 260: 1, 338: 1})
n_rel_and_rec_k:  1
uid:  355
1
n_rec_k:  489
true_k:  [423]
est_k:  [307, 155, 332, 269, 123]
count_value:  Counter({423: 1, 307: 1, 155: 1, 332: 1, 269: 1, 123: 1})
n_rel_and_rec_k:  0
uid:  356
1
n_rec_k:  489
true_k:  [120]
est_k:  [120, 136, 117, 149, 199]
count_va

est_k:  [67, 89, 35, 126, 11]
count_value:  Counter({137: 1, 67: 1, 89: 1, 35: 1, 126: 1, 11: 1})
n_rel_and_rec_k:  0
uid:  419
1
n_rec_k:  489
true_k:  [246]
est_k:  [132, 278, 189, 264, 177]
count_value:  Counter({246: 1, 132: 1, 278: 1, 189: 1, 264: 1, 177: 1})
n_rel_and_rec_k:  0
uid:  420
1
n_rec_k:  489
true_k:  [477]
est_k:  [155, 231, 320, 69, 103]
count_value:  Counter({477: 1, 155: 1, 231: 1, 320: 1, 69: 1, 103: 1})
n_rel_and_rec_k:  0
uid:  421
1
n_rec_k:  489
true_k:  [303]
est_k:  [117, 98, 148, 205, 288]
count_value:  Counter({303: 1, 117: 1, 98: 1, 148: 1, 205: 1, 288: 1})
n_rel_and_rec_k:  0
uid:  422
1
n_rec_k:  489
true_k:  [152]
est_k:  [75, 310, 126, 10, 80]
count_value:  Counter({152: 1, 75: 1, 310: 1, 126: 1, 10: 1, 80: 1})
n_rel_and_rec_k:  0
uid:  423
1
n_rec_k:  489
true_k:  [336]
est_k:  [336, 99, 255, 5, 24]
count_value:  Counter({336: 2, 99: 1, 255: 1, 5: 1, 24: 1})
n_rel_and_rec_k:  1
uid:  424
1
n_rec_k:  424
true_k:  [427]
est_k:  [90, 69, 149, 96, 49]
co

true_k:  [120]
est_k:  [136, 120, 12, 273, 69]
count_value:  Counter({120: 2, 136: 1, 12: 1, 273: 1, 69: 1})
n_rel_and_rec_k:  1
uid:  487
1
n_rec_k:  489
true_k:  [145]
est_k:  [307, 155, 261, 241, 118]
count_value:  Counter({145: 1, 307: 1, 155: 1, 261: 1, 241: 1, 118: 1})
n_rel_and_rec_k:  0
uid:  488
1
n_rec_k:  417
true_k:  [69]
est_k:  [69, 90, 120, 12, 136]
count_value:  Counter({69: 2, 90: 1, 120: 1, 12: 1, 136: 1})
n_rel_and_rec_k:  1
uid:  489
1
n_rec_k:  489
true_k:  [332]
est_k:  [332, 290, 261, 174, 155]
count_value:  Counter({332: 2, 290: 1, 261: 1, 174: 1, 155: 1})
n_rel_and_rec_k:  1
uid:  490
1
n_rec_k:  489
true_k:  [58]
est_k:  [460, 185, 73, 34, 231]
count_value:  Counter({58: 1, 460: 1, 185: 1, 73: 1, 34: 1, 231: 1})
n_rel_and_rec_k:  0
uid:  491
1
n_rec_k:  474
true_k:  [90]
est_k:  [90, 69, 12, 155, 136]
count_value:  Counter({90: 2, 69: 1, 12: 1, 155: 1, 136: 1})
n_rel_and_rec_k:  1
uid:  492
1
n_rec_k:  489
true_k:  [435]
est_k:  [141, 223, 154, 210, 375]
count

true_k:  [12]
est_k:  [58, 170, 71, 98, 113]
count_value:  Counter({12: 1, 58: 1, 170: 1, 71: 1, 98: 1, 113: 1})
n_rel_and_rec_k:  0
uid:  555
1
n_rec_k:  341
true_k:  [90]
est_k:  [90, 69, 207, 124, 49]
count_value:  Counter({90: 2, 69: 1, 207: 1, 124: 1, 49: 1})
n_rel_and_rec_k:  1
uid:  556
1
n_rec_k:  489
true_k:  [429]
est_k:  [421, 148, 436, 23, 309]
count_value:  Counter({429: 1, 421: 1, 148: 1, 436: 1, 23: 1, 309: 1})
n_rel_and_rec_k:  0
uid:  557
1
n_rec_k:  489
true_k:  [370]
est_k:  [370, 270, 197, 12, 344]
count_value:  Counter({370: 2, 270: 1, 197: 1, 12: 1, 344: 1})
n_rel_and_rec_k:  1
uid:  558
1
n_rec_k:  489
true_k:  [477]
est_k:  [103, 434, 148, 24, 99]
count_value:  Counter({477: 1, 103: 1, 434: 1, 148: 1, 24: 1, 99: 1})
n_rel_and_rec_k:  0
uid:  559
1
n_rec_k:  489
true_k:  [182]
est_k:  [412, 355, 141, 318, 405]
count_value:  Counter({182: 1, 412: 1, 355: 1, 141: 1, 318: 1, 405: 1})
n_rel_and_rec_k:  0
uid:  560
1
n_rec_k:  217
true_k:  [171]
est_k:  [171, 8, 336, 

est_k:  [262, 268, 260, 351, 215]
count_value:  Counter({315: 1, 262: 1, 268: 1, 260: 1, 351: 1, 215: 1})
n_rel_and_rec_k:  0
uid:  622
1
n_rec_k:  489
true_k:  [358]
est_k:  [174, 215, 260, 192, 329]
count_value:  Counter({358: 1, 174: 1, 215: 1, 260: 1, 192: 1, 329: 1})
n_rel_and_rec_k:  0
uid:  623
1
n_rec_k:  389
true_k:  [135]
est_k:  [135, 96, 142, 232, 56]
count_value:  Counter({135: 2, 96: 1, 142: 1, 232: 1, 56: 1})
n_rel_and_rec_k:  1
uid:  624
1
n_rec_k:  489
true_k:  [90]
est_k:  [90, 69, 120, 207, 149]
count_value:  Counter({90: 2, 69: 1, 120: 1, 207: 1, 149: 1})
n_rel_and_rec_k:  1
uid:  625
1
n_rec_k:  489
true_k:  [103]
est_k:  [233, 436, 421, 82, 330]
count_value:  Counter({103: 1, 233: 1, 436: 1, 421: 1, 82: 1, 330: 1})
n_rel_and_rec_k:  0
uid:  626
1
n_rec_k:  489
true_k:  [270]
est_k:  [132, 177, 264, 278, 189]
count_value:  Counter({270: 1, 132: 1, 177: 1, 264: 1, 278: 1, 189: 1})
n_rel_and_rec_k:  0
uid:  627
1
n_rec_k:  489
true_k:  [227]
est_k:  [227, 26, 137, 18

est_k:  [159, 246, 321, 338, 261]
count_value:  Counter({246: 2, 159: 1, 321: 1, 338: 1, 261: 1})
n_rel_and_rec_k:  1
uid:  690
1
n_rec_k:  489
true_k:  [90]
est_k:  [12, 69, 120, 136, 242]
count_value:  Counter({90: 1, 12: 1, 69: 1, 120: 1, 136: 1, 242: 1})
n_rel_and_rec_k:  0
uid:  691
1
n_rec_k:  489
true_k:  [355]
est_k:  [245, 355, 278, 333, 356]
count_value:  Counter({355: 2, 245: 1, 278: 1, 333: 1, 356: 1})
n_rel_and_rec_k:  1
uid:  692
1
n_rec_k:  236
true_k:  [171]
est_k:  [171, 64, 8, 336, 111]
count_value:  Counter({171: 2, 64: 1, 8: 1, 336: 1, 111: 1})
n_rel_and_rec_k:  1
uid:  693
1
n_rec_k:  489
true_k:  [171]
est_k:  [261, 139, 58, 88, 140]
count_value:  Counter({171: 1, 261: 1, 139: 1, 58: 1, 88: 1, 140: 1})
n_rel_and_rec_k:  0
uid:  694
1
n_rec_k:  489
true_k:  [69]
est_k:  [136, 69, 90, 12, 120]
count_value:  Counter({69: 2, 136: 1, 90: 1, 12: 1, 120: 1})
n_rel_and_rec_k:  1
uid:  695
1
n_rec_k:  489
true_k:  [413]
est_k:  [111, 8, 16, 22, 179]
count_value:  Counter({

true_k:  [139]
est_k:  [139, 123, 264, 88, 132]
count_value:  Counter({139: 2, 123: 1, 264: 1, 88: 1, 132: 1})
n_rel_and_rec_k:  1
uid:  758
1
n_rec_k:  489
true_k:  [155]
est_k:  [112, 332, 290, 307, 389]
count_value:  Counter({155: 1, 112: 1, 332: 1, 290: 1, 307: 1, 389: 1})
n_rel_and_rec_k:  0
uid:  759
1
n_rec_k:  267
true_k:  [171]
est_k:  [171, 336, 8, 64, 111]
count_value:  Counter({171: 2, 336: 1, 8: 1, 64: 1, 111: 1})
n_rel_and_rec_k:  1
uid:  760
1
n_rec_k:  489
true_k:  [90]
est_k:  [69, 90, 120, 136, 12]
count_value:  Counter({90: 2, 69: 1, 120: 1, 136: 1, 12: 1})
n_rel_and_rec_k:  1
uid:  761
1
n_rec_k:  489
true_k:  [312]
est_k:  [173, 190, 102, 246, 39]
count_value:  Counter({312: 1, 173: 1, 190: 1, 102: 1, 246: 1, 39: 1})
n_rel_and_rec_k:  0
uid:  762
1
n_rec_k:  489
true_k:  [8]
est_k:  [8, 22, 179, 171, 18]
count_value:  Counter({8: 2, 22: 1, 179: 1, 171: 1, 18: 1})
n_rel_and_rec_k:  1
uid:  763
1
n_rec_k:  489
true_k:  [317]
est_k:  [317, 123, 142, 259, 394]
count_va

est_k:  [232, 135, 356, 132, 12]
count_value:  Counter({232: 2, 135: 1, 356: 1, 132: 1, 12: 1})
n_rel_and_rec_k:  1
uid:  825
1
n_rec_k:  489
true_k:  [358]
est_k:  [71, 84, 69, 96, 269]
count_value:  Counter({358: 1, 71: 1, 84: 1, 69: 1, 96: 1, 269: 1})
n_rel_and_rec_k:  0
uid:  826
1
n_rec_k:  447
true_k:  [69]
est_k:  [69, 90, 120, 12, 136]
count_value:  Counter({69: 2, 90: 1, 120: 1, 12: 1, 136: 1})
n_rel_and_rec_k:  1
uid:  827
1
n_rec_k:  489
true_k:  [315]
est_k:  [170, 231, 109, 303, 308]
count_value:  Counter({315: 1, 170: 1, 231: 1, 109: 1, 303: 1, 308: 1})
n_rel_and_rec_k:  0
uid:  828
1
n_rec_k:  489
true_k:  [130]
est_k:  [218, 149, 266, 120, 90]
count_value:  Counter({130: 1, 218: 1, 149: 1, 266: 1, 120: 1, 90: 1})
n_rel_and_rec_k:  0
uid:  829
1
n_rec_k:  489
true_k:  [12]
est_k:  [12, 5, 192, 148, 136]
count_value:  Counter({12: 2, 5: 1, 192: 1, 148: 1, 136: 1})
n_rel_and_rec_k:  1
uid:  830
1
n_rec_k:  489
true_k:  [268]
est_k:  [268, 338, 273, 262, 49]
count_value:  C

KeyboardInterrupt: 